# Generated by Django 5.2.8 on 2025-12-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_orderitem_name_remove_orderitem_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(default='Unknown Product', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='Unknown Product', max_length=255),
            preserve_default=False,
        ),
    ]
