# Generated by Django 5.2.8 on 2025-12-01 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_orderitem_name_product_name'),
        ('api', '0006_add_initial_products2'),
    ]

    operations = [
    ]
